#!/bin/sh -e
# $Id: report-git-statuses,v 1.7 2013/04/19 05:43:46 rcgood Exp $  #%^)

Pname="`exec basename $0`"
Usage="Usage: $Pname"

descDir=descriptor-dir-live

dirList="
$descDir/.ii-user/*/.ii/*
$descDir/.ii-user/*
$descDir/.ii/*
$descDir
.
"

gitPushCmd=''
if [ "$1" = '-push' ]; then
    gitPushCmd='(cd $dir && git push origin && git push public)'
fi


for dir in $dirList; do
    if [ ! -d $dir/.git ]; then
        # echo " -- $Pname: no git repo here: $dir"
        :
    else
        ( cd $dir && git status ) > .st
        files="`grep 'modified:' .st | awk '{print $3}'`"
        files="`echo $files`"

        cat .st

        if [ -n "$files" ]; then
            echo ''
            for f in $files; do echo "    (cd $dir && git diff $f)"; done
            echo "    ./git-add-and-commit $dir $files"
            echo ''
        fi

        rm .st

        eval $gitPushCmd || true
    fi
done

exit
