#!/bin/sh -e
# $Id: report-git-statuses,v 1.3 2013/04/11 22:33:42 rcgood Exp $  #%^)

Pname="`exec basename $0`"
Usage="Usage: $Pname"

descDir=descriptor-dir-live

dirList="
$descDir/.ii-user/*/.ii/*
$descDir/.ii-user/*
$descDir/.ii/*
$descDir
.
"

gitPushCmd=''
if [ "$1" = '-push' ]; then
    gitPushCmd='(cd $dir && git push)'
fi


for dir in $dirList; do
    if [ ! -d $dir/.git ]; then
        # echo " -- $Pname: no git repo here: $dir"
        :
    else
        echo " -- $Pname: dir: $dir"
        ( cd $dir && git status )
        eval $gitPushCmd || true
        echo ''
    fi
done

exit
