#!/bin/sh -e
# $Id: update-lib-timestamp,v 1.3 2013/04/18 17:00:13 rcgood Exp $  #%^)

Pname="`exec basename $0`"
Usage="Usage: $Pname <lib-name>"

descDir=descriptor-dir-live

libName="$1"
if [ -z "$libName" ]; then
    echo " !! $Usage" 1>&2
    exit 1
fi



cd $descDir/.ii/lib-$libName

dpl -eval '(print (desc-to-string (sprintf %010d (time))))' > $libName-timestamp

git add $libName-timestamp
git commit -m 'auto deploy timestamp'

exit
